[package]
name = "FixedPoint64"
version = "0.3.6"

[addresses]
fixed_point64 = "0x2"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "23d258d1f2440267f866eeb27f9830be48682af8"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { std = "0x1" }
